### ISSUE TITLE
Building fails on github.com/spf13/afero with errors

### ISSUE THREAD

**Issue by mexisme** [StuffNZ/get-secrets#1]
I get one of the following errors when trying to build with Go 1.11:

```
% make build  
>> building executable...
go: finding golang.org/x/text/unicode/norm latest
go: finding golang.org/x/text/transform latest
go: finding golang.org/x/text/unicode latest
/home/wj/go/pkg/mod/github.com/spf13/afero@v1.1.2/util.go:28:2: unknown import path "golang.org/x/text/transform": cannot find module providing package golang.org/x/text/transform
/home/wj/go/pkg/mod/github.com/spf13/afero@v1.1.2/util.go:29:2: unknown import path "golang.org/x/text/unicode/norm": cannot find module providing package golang.org/x/text/unicode/norm
make: *** [Makefile:39: build] Error 1
```

```
% go get -u ./...
go: finding gopkg.in/check.v1 latest
go: finding github.com/certifi/gocertifi latest
go: finding github.com/gopherjs/gopherjs latest
go: finding gopkg.in/tomb.v1 latest
go: finding golang.org/x/sys latest
go: finding github.com/smartystreets/goconvey latest
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/jmespath/go-jmespath latest
go: finding golang.org/x/net latest
go: finding golang.org/x/crypto latest
go: finding github.com/aws/aws-sdk-go v1.15.72
go: finding golang.org/x/sync latest
go: finding github.com/smartystreets/assertions latest
go: finding github.com/sirupsen/logrus v1.2.0
go: finding github.com/stretchr/objx v0.1.1
go: downloading github.com/aws/aws-sdk-go v1.15.72
go: downloading github.com/sirupsen/logrus v1.2.0
go: downloading github.com/spf13/cast v1.3.0
go: downloading golang.org/x/sys v0.0.0-20181107165924-66b7b1311ac8
go: downloading golang.org/x/crypto v0.0.0-20181106171534-e4dc69e5b2fd
go: finding golang.org/x/text/transform latest
go: finding golang.org/x/text/unicode/norm latest
go: finding golang.org/x/text/unicode latest
go build golang.org/x/text/transform: no Go files in 
go build golang.org/x/text/unicode/norm: no Go files in 
```

This seems like it might be related to https://github.com/golang/go/issues/27556.

**Comment by mexisme** [comment]
Actually, it appears to be related to:
https://github.com/golang/go/issues/27565

Whereby the Go 1.11 mod cache needs to be cleared out.
